name: Package Application with Pyinstaller

on:
  push:
    branches: [ exe ]
  pull_request:
    branches: [ exe ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: canvassyncer

    - uses: actions/upload-artifact@v2
      with:
        name: CanvasSyncer
        path: src/dist/windows
